music_directory = 'H:\music'
cover_names = ["cover", "folder", "album", "front", "art"]
cover_extensions = ["jpg", "jpeg", "png"]
audio_extensions = ["mp3", "flac", "opus", "ogg", "m4a", "mp4", "wav", "aac", "alac"]
window_size = [800, 600]
startup_view = "cover"

[shortcuts]
LoopB = "]"
Help = "H"
ClearLoop = '\'
ReconnectAudio = "F6"
Rescan = "F5"
NowPlaying = "F2"
Select = "Enter"
Forward = "'"
NavigateLeft = "ArrowLeft"
NavigateUp = "ArrowUp"
Escape = "Escape"
RecentAlbums = "B"
OpenFolder = "O"
NavigateRight = "ArrowRight"
YearBrowse = "Y"
ComposerBrowse = "C"
VolumeDown = "-"
Rewind = ";"
TrackDetails = "I"
LoopA = "["
GenreBrowse = "G"
ShuffleToggle = "F8"
WaveformOpen = "0"
ToggleView = "T"
AppendQueue = "A"
ClearMarks = "Shift+M"
CompactToggle = "F11"
Skip = "N"
SearchMode = "/"
RepeatToggle = "X"
QueueToggle = "Q"
VolumeUp = "="
SortToggle = "S"
RescanMarked = "Shift+R"
MarkTrack = "M"
WaveformSaveLoop = "Ctrl+S"
RandomAlbum = "R"
NavigateDown = "ArrowDown"
PlayPause = "Space"
SelectionBrowse = "Z"
